version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: "pip"
    directory: "/"
    exclude-paths:
      - "docs/**"
    schedule:
      interval: "weekly"
    groups:
      python:
        patterns: ["*"]
    commit-message:
      prefix: "chore"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    groups:
      documentation:
        patterns: ["*"]
    ignore:
      - dependency-name: "sphinx"
        update-types: ["version-update:semver-major"]
      - dependency-name: "myst-parser"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "docs"
