# SPDX-License-Identifier: CeCILL-2.1 OR AGPL-3.0-or-later
"""Reusable HTML fragments: nav, footer, hero (spectral-wave), KPIs, paper card, pipeline, references.

The hero markup + spectral-wave animation are adapted from the shared family chrome
(``nirs4all.org`` / ``nirs4all-datasets``). Everything else is authored for the papers site. Pure
string builders over the escaping helpers + view models; nothing touches the filesystem or nirs4all.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

from .. import __version__
from ..bibliography import Reference
from .escape import esc, locator_link

if TYPE_CHECKING:
    from ..model import PaperView

GITHUB = "https://github.com/GBeurier/nirs4all-papers"
_NAV_VER = "v" + ".".join(__version__.split(".")[:2])  # e.g. "v0.2"


# ── Nav + footer ─────────────────────────────────────────────────────────
def nav(rel: str, active: str = "") -> str:
    def cls(name: str) -> str:
        return ' class="active"' if name == active else ""

    return f"""
<nav id="nav"><div class="container nav-inner">
  <a class="nav-logo" href="{rel}index.html"><img class="nav-mark" src="{rel}brand/icon.svg" alt="nirs4all-papers" width="28" height="28"><span class="nav-name"><b>nirs4all</b>-papers</span><span class="nav-ver">{_NAV_VER}</span></a>
  <div class="nav-links">
    <a href="{rel}index.html"{cls('index')}>Overview</a>
    <a href="{rel}catalog.html"{cls('catalog')}>Papers</a>
    <a href="https://nirs4all.org" target="_blank" rel="noopener">nirs4all.org</a>
    <a href="{GITHUB}" target="_blank" rel="noopener">GitHub</a>
  </div>
</div></nav>
"""


def footer(rel: str) -> str:
    return f"""
<footer><div class="container">
  <div>
    <div class="f-brand">nirs4all-papers</div>
    <p class="f-meta">Public, permanent reproduction documents for deposited nirs4all papers — the
    exact pipeline, its methods and bibliography, a live in-browser replay, and machine-readable
    deposit sidecars (CITATION.cff, BibTeX, RO-Crate).</p>
  </div>
  <div class="f-links">
    <a href="{rel}index.html">Overview</a>
    <a href="{rel}catalog.html">Papers</a>
    <a href="{GITHUB}" target="_blank" rel="noopener">Source &amp; issues</a>
    <a href="https://nirs4all.org" target="_blank" rel="noopener">nirs4all ecosystem</a>
  </div>
  <p class="f-note">Generated by the nirs4all-papers reproduction-document publisher — pure rendering
  over a deposited <code>.n4a</code> bundle. Deposited manuscripts keep their publisher's terms;
  datasets keep their own license / DOI terms.</p>
</div></footer>
"""


# ── Hero (spectral-wave) ─────────────────────────────────────────────────
def hero(n_papers: int, n_methods: int) -> str:
    return """
<section id="hero">
  <div class="hero-dots"></div>
  <svg class="hero-spectra" viewBox="0 0 1440 400" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
    <path class="spectrum-line" id="line0" stroke="#0f766e" stroke-width="1.3" opacity="0.75"/>
    <path class="spectrum-line" id="line1" stroke="#0891b2" stroke-width="1.0" opacity="0.55"/>
    <path class="spectrum-line" id="line2" stroke="#059669" stroke-width="0.8" opacity="0.35"/>
    <g id="wave-dots"></g>
  </svg>
  <div class="container hero-content">
    <img class="hero-logo" src="brand/horizontal.svg" alt="nirs4all-papers" width="460">
    <div class="hero-badge"><span class="dot"></span> deposited · cited · re-runnable in the browser</div>
    <h1 class="hero-tagline">Every published pipeline, <em>reproducible</em></h1>
    <p class="hero-sub">Each nirs4all paper becomes a self-contained reproduction document — the exact
    preprocessing and model, a bibliography for every method, the protocol and scores, and a
    <strong>live replay</strong> that re-runs the pipeline in your browser.</p>
    <div class="hero-ctas">
      <a class="btn btn-primary" href="catalog.html">Browse the papers &rarr;</a>
      <a class="btn btn-outline" href="https://nirs4all.org" target="_blank" rel="noopener">nirs4all.org</a>
    </div>
  </div>
</section>
"""


HERO_SCRIPT = """
<script>
(function(){
  var W=1440,H=400,STEP=4;
  var lines=[document.getElementById('line0'),document.getElementById('line1'),document.getElementById('line2')];
  var dotsGroup=document.getElementById('wave-dots');
  if(!lines[0]||!dotsGroup)return;
  var waves=[
    {baseY:260,amp:50,freq:0.0044,phase:0,speed:0.00035,color:'#0f766e',dotColor:'rgba(15,118,110,0.95)'},
    {baseY:290,amp:38,freq:0.0038,phase:2.1,speed:0.00028,color:'#0891b2',dotColor:'rgba(8,145,178,0.85)'},
    {baseY:230,amp:30,freq:0.0052,phase:4.2,speed:0.00022,color:'#059669',dotColor:'rgba(5,150,105,0.75)'}
  ];
  var MAX_DOTS=16,dots=[],DOT_LIFETIME=2400,DOT_SPAWN_INTERVAL=340,lastSpawn=0;
  var svgEl=lines[0].ownerSVGElement,invSx=1,invSy=1;
  function updateScale(){var r=svgEl.getBoundingClientRect();if(r.width>0&&r.height>0){invSx=W/r.width;invSy=H/r.height;}}
  updateScale();window.addEventListener('resize',updateScale);
  function getY(w,x,now){return w.baseY+Math.sin(x*w.freq+w.phase+now*w.speed)*w.amp+Math.sin(x*w.freq*1.7+w.phase*0.6+now*w.speed*0.7)*w.amp*0.2;}
  function buildPath(w,now){var d='';for(var x=0;x<=W;x+=STEP){var y=getY(w,x,now);d+=(x===0?'M':'L')+x.toFixed(1)+','+y.toFixed(1);}return d;}
  function spawnDot(now){if(dots.length>=MAX_DOTS)return;var wi=Math.floor(Math.random()*waves.length),w=waves[wi];
    var x=60+Math.random()*(W-120),y=getY(w,x,now);
    var el=document.createElementNS('http://www.w3.org/2000/svg','ellipse');
    el.setAttribute('cx',x.toFixed(1));el.setAttribute('cy',y.toFixed(1));
    el.setAttribute('rx',(3*invSx).toFixed(2));el.setAttribute('ry',(3*invSy).toFixed(2));
    el.setAttribute('fill',w.dotColor);el.setAttribute('opacity','0');el.classList.add('wave-dot');el.style.color=w.color;
    dotsGroup.appendChild(el);dots.push({el:el,waveIdx:wi,x:x,born:now,lifetime:DOT_LIFETIME+Math.random()*800});}
  function updateDots(now){for(var i=dots.length-1;i>=0;i--){var dot=dots[i],age=now-dot.born,p=age/dot.lifetime;
    if(p>=1){dot.el.remove();dots.splice(i,1);continue;}
    var y=getY(waves[dot.waveIdx],dot.x,now);dot.el.setAttribute('cy',y.toFixed(1));
    var op;if(p<0.15)op=p/0.15;else if(p<0.7)op=1;else op=1-(p-0.7)/0.3;
    dot.el.setAttribute('opacity',(op*0.9).toFixed(3));var r=2.5+op*1.5;
    dot.el.setAttribute('rx',(r*invSx).toFixed(2));dot.el.setAttribute('ry',(r*invSy).toFixed(2));}}
  var frameId=0;
  function animate(now){waves.forEach(function(w,i){lines[i].setAttribute('d',buildPath(w,now));});
    if(now-lastSpawn>DOT_SPAWN_INTERVAL){spawnDot(now);lastSpawn=now;}
    updateDots(now);frameId=requestAnimationFrame(animate);}
  frameId=requestAnimationFrame(animate);
  window.addEventListener('pagehide',function(){cancelAnimationFrame(frameId);},{once:true});
})();
</script>
"""


# ── Small chips / KPIs / heads ───────────────────────────────────────────
_KPI_ACCENTS = ["var(--teal)", "var(--cyan)", "var(--indigo)", "var(--amber)", "var(--green)", "var(--teal-d)"]


def kpi_strip(kpis: list[tuple[str, str]]) -> str:
    cells = "".join(
        f'<div class="kpi" style="--accent:{_KPI_ACCENTS[i % len(_KPI_ACCENTS)]}">'
        f'<div class="kpi-v">{esc(value)}</div><div class="kpi-l">{esc(label)}</div></div>'
        for i, (value, label) in enumerate(kpis)
    )
    return f'<div class="kpis">{cells}</div>'


def badge(text: str, kind: str = "neutral", *, dot: bool = False) -> str:
    d = '<span class="b-dot"></span>' if dot else ""
    return f'<span class="badge {esc(kind)}">{d}{esc(text)}</span>'


def section_head(eyebrow: str, title_html: str, sub: str = "") -> str:
    sub_html = f'<p class="section-sub">{esc(sub)}</p>' if sub else ""
    return f'<div class="eyebrow-wrap"><span class="eyebrow">{esc(eyebrow)}</span></div><h2 class="section-title">{title_html}</h2>{sub_html}'


def code_block(lines: list[tuple[str, str]]) -> str:
    rendered = []
    for cls, text in lines:
        rendered.append(f'<span class="{cls}">{esc(text)}</span>' if cls else esc(text))
    return f'<div class="codeblock"><div class="topbar"><i></i><i></i><i></i></div><pre>{chr(10).join(rendered)}</pre></div>'


_STATUS_KIND = {"published": "ok", "accepted": "ok", "preprint": "info", "deposited": "accent"}


def status_badge(status: str) -> str:
    return badge(status, _STATUS_KIND.get(status.lower(), "neutral") + " status-pill", dot=True)


# ── Catalog card ─────────────────────────────────────────────────────────
def paper_card(view: PaperView) -> str:
    model = view.model_step
    model_name = model.info.short_name if model else "—"
    primary_metric = view.metrics[0] if view.metrics else None
    metric_str = f"{primary_metric.name} {esc(_short(primary_metric.value))}" if primary_metric else "—"
    badges = [status_badge(view.status)]
    if view.doi:
        badges.append(badge("DOI", "neutral"))
    badges.append(badge(f"{len(view.references)} refs", "neutral"))
    if view.replay:
        badges.append(badge("live replay", "ok", dot=True))

    search = " ".join([view.title.lower(), view.authors_line.lower(), str(view.venue or "").lower(), " ".join(view.keywords).lower(), model_name.lower()])
    data = (
        f'data-name="{esc(search)}" data-status="{esc(view.status)}" '
        f'data-model="{esc(model_name)}" data-year="{esc(str(view.year or 0))}" data-refs="{len(view.references)}"'
    )
    venue = f'<div class="p-venue">{esc(view.venue)}{(" · " + esc(str(view.year))) if view.year else ""}</div>' if view.venue else ""
    return f"""
<article class="p-card" {data}>
  <h3><a href="paper/{esc(view.slug)}.html">{esc(view.title)}</a></h3>
  <div class="p-authors">{esc(view.authors_line) or "—"}</div>
  {venue}
  <div class="p-meta">
    <div>Model <b>{esc(model_name)}</b></div>
    <div>{esc(metric_str)}</div>
    <div>Steps <b>{view.n_steps}</b></div>
  </div>
  <div class="p-badges">{"".join(badges)}</div>
</article>
"""


# ── Pipeline steps ───────────────────────────────────────────────────────
_NUM_BG = {
    "preprocessing": "var(--k-pre)",
    "target": "var(--k-target)",
    "model": "var(--k-model)",
    "split": "var(--k-split)",
}
_KIND_LABEL = {
    "preprocessing": "preprocessing",
    "target": "target transform",
    "model": "model",
    "split": "split / cv",
}


def pipeline_steps(view: PaperView, rel: str) -> str:
    rows: list[str] = []
    for sv in view.steps:
        kind = sv.info.kind
        num_bg = _NUM_BG.get(kind, "var(--k-split)")
        cite = ""
        if sv.reference and sv.reference.number:
            cite = f'<sup class="cite-sup"><a href="#ref-{sv.reference.number}" title="{esc(sv.reference.label)}">[{sv.reference.number}]</a></sup>'
        params = ""
        if sv.info.params:
            chips = "".join(f"<code>{esc(k)}={esc(_short(v))}</code>" for k, v in sv.info.params.items())
            params = f'<div class="pipe-params">{chips}</div>'
        note = '<div class="pipe-note">internal splitter — re-derived at fit time, not a stored transform</div>' if not sv.info.reproducible else ""
        desc = ""
        if sv.principle:
            desc = f'<div class="pipe-desc">{esc(sv.principle)}</div>'
        rows.append(
            f'<div class="pipe-step">'
            f'<div class="pipe-rail"><div class="pipe-num" style="background:{num_bg}">{sv.info.index}</div><div class="pipe-line"></div></div>'
            f'<div class="pipe-body k-{kind}">'
            f'<div class="pipe-head"><span class="pipe-name">{esc(sv.info.short_name)}</span>{cite}'
            f'<span class="pipe-kind k-{kind}">{esc(_KIND_LABEL.get(kind, kind))}</span></div>'
            f'<div class="pipe-fqn">{esc(sv.info.raw)}</div>{desc}{params}{note}</div></div>'
        )
    return f'<div class="pipe">{"".join(rows)}</div>'


def copy_button(target_id: str, label: str = "copy") -> str:
    """A copy-to-clipboard button bound (via COPY_JS) to the element id ``target_id``."""
    return f'<button class="copy-btn" data-copy="{esc(target_id)}" aria-label="copy to clipboard">{esc(label)}</button>'


# ── References ───────────────────────────────────────────────────────────
def reference_item(ref: Reference) -> str:
    bits: list[str] = []
    if ref.authors:
        bits.append(esc(ref.authors))
    if ref.year:
        bits.append(f"({ref.year})")
    body = " ".join(bits)
    venue = f" {esc(ref.venue)}." if ref.venue else ""
    link = f' {locator_link(ref.doi or ref.url)}' if (ref.doi or ref.url) else ""
    principle = f'<span class="ref-principle">{esc(ref.principle)}</span>' if ref.principle else ""
    return (
        f'<li id="ref-{ref.number}"><span class="ref-num">[{ref.number}]</span>'
        f'<span class="ref-body">{body} <span class="ref-title">{esc(ref.title)}.</span>{venue}{link}{principle}</span></li>'
    )


def reference_list(refs: list[Reference]) -> str:
    if not refs:
        return '<p class="dl-note">No method in this pipeline maps to a curated reference yet.</p>'
    return f'<ol class="reflist">{"".join(reference_item(r) for r in refs)}</ol>'


def _short(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.4g}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_short(v) for v in value) + "]"
    return str(value)


def metric_value(value: object) -> str:
    return _short(value) if value is not None else "—"
